### ISSUE TITLE
ruminant poop does not work with start/end time defined

### ISSUE THREAD

**Issue by friedlsa** [unprofession-al/ruminant#2] opened 2018-10-30 14:10 UTC
ruminant -c lsv.yaml poop                                                                                    master 
time,channel,quality,protocol,secure,transport,ch,codec,bytes_sent,concurrent,br
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/unprofession-al/ruminant/cmd.glob..func5(0xa794c0, 0xc4201103e0, 0x0, 0x2)                                                                                   
        /home/sam/Documents/devel/go/src/github.com/unprofession-al/ruminant/cmd/cmd_poop.go:58 +0xf2e                                                                  
github.com/unprofession-al/ruminant/vendor/github.com/spf13/cobra.(*Command).execute(0xa794c0, 0xc4201103c0, 0x2, 0x2, 0xa794c0, 0xc4201103c0)                          
        /home/sam/Documents/devel/go/src/github.com/unprofession-al/ruminant/vendor/github.com/spf13/cobra/command.go:654 +0x2a2                                        
github.com/unprofession-al/ruminant/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa79700, 0x74fe5f, 0x0, 0xa79940)                                                
        /home/sam/Documents/devel/go/src/github.com/unprofession-al/ruminant/vendor/github.com/spf13/cobra/command.go:729 +0x2d4                                        
github.com/unprofession-al/ruminant/vendor/github.com/spf13/cobra.(*Command).Execute(0xa79700, 0xc42007a058, 0x0)                                                       
        /home/sam/Documents/devel/go/src/github.com/unprofession-al/ruminant/vendor/github.com/spf13/cobra/command.go:688 +0x2b                                         
github.com/unprofession-al/ruminant/cmd.Execute()
        /home/sam/Documents/devel/go/src/github.com/unprofession-al/ruminant/cmd/cmd_root.go:25 +0x2d                                                                   
main.main()
        /home/sam/Documents/devel/go/src/github.com/unprofession-al/ruminant/main.go:20 +0x20

**Comment by sontags** [comment] 2019-09-27 13:10
@friedlsa I do not exactly understand the issue: What do you mean by "with start/end time defined"?

However the issue is rather clear: https://github.com/unprofession-al/ruminant/blob/master/cmd/cmd_poop.go#L58

Ruminant expects to get at least on result. I your case the query (against InfluxDB) returned no results which caused ruminant to crash. I will fix this asap.

**Comment by sontags** [comment] 2019-10-11 05:29
Merged, closing this

**Closed as completed by sontags** 2019-10-11 05:29 UTC
